language: python
python:
  - "2.7"
  - "pypy"
install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install coverage
  - pip install mock
  - pip install coveralls
  - pip install .
before_script:
  - wget http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz -O /tmp/dynamodb_local_latest.tar.gz
  - tar -xzf /tmp/dynamodb_local_latest.tar.gz -C /tmp
  - java -Djava.library.path=/tmp/DynamoDBLocal_lib -jar /tmp/DynamoDBLocal.jar -inMemory &
  - sleep 5
script:
  - coverage run --source stss -m py.test
after_success:
  - coveralls
services:
  - redis-server
